<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Products</name>
   <tag></tag>
   <elementGuidId>5918161f-1705-4418-a059-f2ca6e379bd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.level-1-item > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-nav']/li[2]/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d43b2b43-b89b-4d61-8da2-3948ba61edad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Products</value>
      <webElementGuid>b1cd9c64-83bb-4205-ac58-18b9d3aa2ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-nav&quot;)/li[2]/div[@class=&quot;level-1-item-container desktop-active&quot;]/a[@class=&quot;level-1-item&quot;]/span[1]</value>
      <webElementGuid>3553c6c5-57bd-4392-a453-e54a02d6efbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-nav']/li[2]/div/a/span</value>
      <webElementGuid>42a8185b-905c-403c-b00e-d1db5579b11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Climate Technologies'])[2]/following::span[1]</value>
      <webElementGuid>2a2f7a34-3520-4e28-9b6f-78ea922898be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[2]/following::span[1]</value>
      <webElementGuid>07bb29d9-9d7f-4b8a-88ef-9ff57037b4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[9]/preceding::span[1]</value>
      <webElementGuid>ab05430b-15b3-44d6-8ba5-76dfab0838fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[10]/preceding::span[2]</value>
      <webElementGuid>1757eaa6-073a-49d1-a1df-e84caa6061c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/div/a/span</value>
      <webElementGuid>019b6ae6-5839-49e5-8d01-b52f1065874d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Products' or . = 'Products')]</value>
      <webElementGuid>f7fbec8e-6078-4bde-a534-acb00428fc54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
