<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_logonPassword</name>
   <tag></tag>
   <elementGuidId>8bcd5767-ca31-4d17-91b8-9ae3bffb0c8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WC_AccountDisplay_FormInput_logonPassword_In_Logon_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WC_AccountDisplay_FormInput_logonPassword_In_Logon_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>357c8180-0873-4379-bf1f-b1f587a63dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-padding</value>
      <webElementGuid>f52c2563-03b9-485e-b00f-1aa208862c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>935ef959-ae24-4b68-a78e-8d4825ac8699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>9dbd24fe-6237-42a9-b4b4-a682394bd12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>logonPassword</value>
      <webElementGuid>810c30ec-97ca-4524-9e6b-9518d53be7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d21cc66b-f771-4088-877e-f9f28f84dda3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>59a0bebb-78ee-40fe-b9ad-64f69ea27129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WC_AccountDisplay_FormInput_logonPassword_In_Logon_1</value>
      <webElementGuid>5536365d-3212-43b7-bdd4-1307687a3ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if(event.keyCode==13){ javascript:setDeleteCartCookie();validateForm();}</value>
      <webElementGuid>27e54c78-be0e-416c-a651-a5e6c7d40f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WC_AccountDisplay_FormInput_logonPassword_In_Logon_1&quot;)</value>
      <webElementGuid>437a652a-3f86-4984-9708-542a0ce3c32d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WC_AccountDisplay_FormInput_logonPassword_In_Logon_1']</value>
      <webElementGuid>9faf5c08-9b5b-42a2-8e79-594cb17e6408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WC_AccountDisplay_div_7']/div[5]/div/input</value>
      <webElementGuid>7edb23bf-9fa5-406f-b5c1-e74101a58e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>4176287c-eced-4fd7-b9ff-4a87752c9965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'logonPassword' and @type = 'password' and @id = 'WC_AccountDisplay_FormInput_logonPassword_In_Logon_1']</value>
      <webElementGuid>0bd36082-a90a-4f10-b142-3f42d44c3c1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
