<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_logonId</name>
   <tag></tag>
   <elementGuidId>94b78f04-b710-4634-83c5-4f33c4b51bea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WC_AccountDisplay_FormInput_logonId_In_Logon_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WC_AccountDisplay_FormInput_logonId_In_Logon_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c9f1554-d344-4f52-a827-af84fdb0460b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-padding</value>
      <webElementGuid>2272473c-1fca-4ad9-8838-cffede6ed0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>169ecd75-b1cf-4fb1-80fe-c3797b570979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>5e7c8f0b-6794-4f1f-a9e2-e856a113912a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61086e6d-ca06-4b6e-9ab4-c39bbc02f6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>logonId</value>
      <webElementGuid>03085a71-5fa5-4f35-802f-484c3e680eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WC_AccountDisplay_FormInput_logonId_In_Logon_1</value>
      <webElementGuid>ebd48add-cff5-4092-93eb-4af4b1aaace8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if(event.keyCode==13){ javascript:setDeleteCartCookie();validateForm();}</value>
      <webElementGuid>bc323bbc-e06e-4a6f-a50b-da6fd3280ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WC_AccountDisplay_FormInput_logonId_In_Logon_1&quot;)</value>
      <webElementGuid>fa65dd83-5424-48bc-99f0-848e43063609</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WC_AccountDisplay_FormInput_logonId_In_Logon_1']</value>
      <webElementGuid>0e45b2bd-002e-428e-9a6f-40760ca7bfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WC_AccountDisplay_div_7']/div[4]/div/input</value>
      <webElementGuid>91ac4e24-b492-4885-9812-3931a48bdeae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>519fadd2-9587-476c-b614-e33f79aadd23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'logonId' and @id = 'WC_AccountDisplay_FormInput_logonId_In_Logon_1']</value>
      <webElementGuid>e9a3c923-4001-40f1-aad2-79dd939df6a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
