<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_logonPassword</name>
   <tag></tag>
   <elementGuidId>4482e877-0c30-442e-9e6f-5cdde06a86a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WC_AccountDisplay_FormInput_logonPassword_In_Logon_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WC_AccountDisplay_FormInput_logonPassword_In_Logon_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d7d89e3-ffd4-4cc0-84de-415f8dbcd33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-padding</value>
      <webElementGuid>dded2f08-f17c-4347-9e62-86af43b878a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21c0edc2-8555-4a86-816e-7b1ff6b370e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>abceee0d-0342-444e-833c-c2425ec4d05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>logonPassword</value>
      <webElementGuid>e5250345-433c-49eb-b197-b8762270bdda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>963a0795-741d-442f-b46f-1b281ad7f2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>796d453c-f692-44a1-9846-0d55a62c71cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WC_AccountDisplay_FormInput_logonPassword_In_Logon_1</value>
      <webElementGuid>0f646590-8b1d-4c88-a84e-ea680d3d2416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if(event.keyCode==13){ javascript:setDeleteCartCookie();validateForm();}</value>
      <webElementGuid>d4fc0b7d-bb23-43a4-a7f4-d0aca7e38126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WC_AccountDisplay_FormInput_logonPassword_In_Logon_1&quot;)</value>
      <webElementGuid>c085dfdb-e707-4df7-acae-122749ef0a45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WC_AccountDisplay_FormInput_logonPassword_In_Logon_1']</value>
      <webElementGuid>38581120-ebfc-4bb9-b83a-04eab85d0595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WC_AccountDisplay_div_7']/div[5]/div/input</value>
      <webElementGuid>67fff588-abd1-4234-9538-6040b082cb3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>4bff94b8-d365-4f0b-afb8-35f223f1cfba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'logonPassword' and @type = 'password' and @id = 'WC_AccountDisplay_FormInput_logonPassword_In_Logon_1']</value>
      <webElementGuid>3edeb8e9-ee29-4ce6-ad6b-27cb4c125ac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
