<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_logonId</name>
   <tag></tag>
   <elementGuidId>39a54b0e-dfdb-4ff8-89a7-2688e4eb4759</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WC_AccountDisplay_FormInput_logonId_In_Logon_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WC_AccountDisplay_FormInput_logonId_In_Logon_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddfbd52c-78b1-404d-9330-4c42b33af4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-padding</value>
      <webElementGuid>be98f542-f9c4-4a7b-ae1d-701e328c3e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d2a4ee75-04f2-40af-8596-4c59978fb317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>ff9c5fa9-d707-4ac3-8723-877993059f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce696e20-cdac-4448-a68b-b27be45f9caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>logonId</value>
      <webElementGuid>6c7ede59-22cd-49cb-b79f-8783cf4cd10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WC_AccountDisplay_FormInput_logonId_In_Logon_1</value>
      <webElementGuid>70245a72-d00b-4352-ba7e-adeb121e7e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if(event.keyCode==13){ javascript:setDeleteCartCookie();validateForm();}</value>
      <webElementGuid>058eddd4-9042-43a8-80d3-b481a31116b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WC_AccountDisplay_FormInput_logonId_In_Logon_1&quot;)</value>
      <webElementGuid>18c874f8-f9df-4514-a757-d62656c977a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WC_AccountDisplay_FormInput_logonId_In_Logon_1']</value>
      <webElementGuid>c2f0eb89-e7ea-48ee-b6bb-87177a293993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WC_AccountDisplay_div_7']/div[4]/div/input</value>
      <webElementGuid>9771f56a-4d10-42c6-bdd9-9ea6c4ea2370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>5dd12661-8107-4628-baf4-cf4369ebf047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'logonId' and @id = 'WC_AccountDisplay_FormInput_logonId_In_Logon_1']</value>
      <webElementGuid>c0c2eb45-6bb8-4d3a-a242-654c593941c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
