<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Careers</name>
   <tag></tag>
   <elementGuidId>0bd2320d-3dc6-425f-9f8c-0c2a5df11133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='cm-header']/nav/div/div/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>93ed2bf3-6ff3-4a02-a7f9-43de23157cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.emerson.com/en-us/careers?_gl=1*k2em5x*_ga*MTUwOTg1ODIyMS4xNjUwODgxMTQ2*_ga_NW3KVPE6D0*MTY1MDg4MTE0NS4xLjEuMTY1MDg4MTE1Ni4w</value>
      <webElementGuid>04d4cdeb-2835-4e76-9a33-0a934eada3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a38bace1-27a7-4921-8b05-4d5d605dc9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Careers</value>
      <webElementGuid>52ba86e7-078d-4c41-9fc1-9a0c9d8781bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cm-header&quot;)/nav[@class=&quot;utility-nav&quot;]/div[@class=&quot;padded-container&quot;]/div[@class=&quot;hidden-xs hidden-sm&quot;]/ul[@class=&quot;horizontal-list&quot;]/li[4]/a[1]</value>
      <webElementGuid>584e9b92-30ab-40d2-b9f0-3e4cf0c07d9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='cm-header']/nav/div/div/ul/li[4]/a</value>
      <webElementGuid>3caa810a-6d12-44fe-8177-09c0bbf58e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Careers')]</value>
      <webElementGuid>780c693e-d3b2-4c8f-9b54-194246a48796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investors'])[1]/following::a[1]</value>
      <webElementGuid>5c845b1f-6fc9-438b-a96e-02b51461d7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/following::a[2]</value>
      <webElementGuid>fbd202c5-08e6-49a7-b6a0-2809f00c245e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[1]</value>
      <webElementGuid>3b73d153-4c59-44f9-9225-4cac18002405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News &amp; Events'])[1]/preceding::a[2]</value>
      <webElementGuid>df702bf7-f24d-4409-89fd-5ce3dabb711e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Careers']/parent::*</value>
      <webElementGuid>90f0900c-4024-4ea6-848d-cd71247827ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.emerson.com/en-us/careers?_gl=1*k2em5x*_ga*MTUwOTg1ODIyMS4xNjUwODgxMTQ2*_ga_NW3KVPE6D0*MTY1MDg4MTE0NS4xLjEuMTY1MDg4MTE1Ni4w')]</value>
      <webElementGuid>49de584e-daea-42c5-9b34-a1d32e3424dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>53539656-2a7f-4c1a-8834-63198a88f54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.emerson.com/en-us/careers?_gl=1*k2em5x*_ga*MTUwOTg1ODIyMS4xNjUwODgxMTQ2*_ga_NW3KVPE6D0*MTY1MDg4MTE0NS4xLjEuMTY1MDg4MTE1Ni4w' and (text() = 'Careers' or . = 'Careers')]</value>
      <webElementGuid>08211e73-6075-45df-a9ce-81c08dc1dd4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
