<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Emerson.com</name>
   <tag></tag>
   <elementGuidId>764388eb-e575-413f-bb90-f34bf9dc5ff3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='cm-header']/nav/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.left-link > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad387c42-76ff-43ec-b87b-b17b739f6b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.emerson.com/?_gl=1*1c7iauh*_ga*MTUwOTg1ODIyMS4xNjUwODgxMTQ2*_ga_NW3KVPE6D0*MTY1MDg4MTE0NS4xLjEuMTY1MDg4MTE1OS4w</value>
      <webElementGuid>f58a2c90-5ff1-4386-b6ea-b36fb8bb7c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>2abf1282-e166-40c1-8c7a-e997ad201ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Emerson.com</value>
      <webElementGuid>824562fe-33e9-43e7-9306-d0a8d4f17f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cm-header&quot;)/nav[@class=&quot;utility-nav&quot;]/div[@class=&quot;padded-container&quot;]/div[@class=&quot;hidden-xs hidden-sm&quot;]/ul[@class=&quot;horizontal-list&quot;]/li[@class=&quot;left-link&quot;]/a[1]</value>
      <webElementGuid>10e17998-e3a7-401f-bb51-bdc4342606a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='cm-header']/nav/div/div/ul/li/a</value>
      <webElementGuid>87b25d58-09ed-4472-8ee3-aebba7c46ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Emerson.com')]</value>
      <webElementGuid>4204319e-7ef1-40b8-910c-89c4b1237cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Search'])[1]/following::a[1]</value>
      <webElementGuid>1f621505-e8af-4a4b-86b9-698f8dc33253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Content'])[1]/following::a[2]</value>
      <webElementGuid>cc5bfc77-3964-427a-9aa4-118719cfff25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::a[1]</value>
      <webElementGuid>bc1daf28-65fc-428f-b6e4-4243c062c00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investors'])[1]/preceding::a[2]</value>
      <webElementGuid>51c9fd42-d8df-443d-ba76-8f6b7ea7f563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Emerson.com']/parent::*</value>
      <webElementGuid>7e6b34f3-2b7e-4ef1-a6f4-14e37fa958bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.emerson.com/?_gl=1*1c7iauh*_ga*MTUwOTg1ODIyMS4xNjUwODgxMTQ2*_ga_NW3KVPE6D0*MTY1MDg4MTE0NS4xLjEuMTY1MDg4MTE1OS4w')]</value>
      <webElementGuid>5e9caf23-9f99-4f99-bf69-56d0acb3e9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li/a</value>
      <webElementGuid>a299d4e0-1628-4cdd-a2cb-fa92b35bd881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.emerson.com/?_gl=1*1c7iauh*_ga*MTUwOTg1ODIyMS4xNjUwODgxMTQ2*_ga_NW3KVPE6D0*MTY1MDg4MTE0NS4xLjEuMTY1MDg4MTE1OS4w' and (text() = 'Emerson.com' or . = 'Emerson.com')]</value>
      <webElementGuid>b5aec66b-43cf-4d7c-9f70-4e684ac163bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
