<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Investors</name>
   <tag></tag>
   <elementGuidId>80ab607f-6c55-489f-a1bb-1a0e80dd2b61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='cm-header']/nav/div/div/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8bc61214-fe1f-4b04-8e44-299ab5cc1e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.emerson.com/en-us/investors?_gl=1*ytxawz*_ga*MTUwOTg1ODIyMS4xNjUwODgxMTQ2*_ga_NW3KVPE6D0*MTY1MDg4MTE0NS4xLjEuMTY1MDg4MTE1NC4w</value>
      <webElementGuid>db0e06e4-3e95-4df1-bbb1-646e314fca73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>9676c3b8-2886-4dd2-bebd-9cf9c5604c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Investors</value>
      <webElementGuid>43250103-477a-43b2-9515-d8a8b6f0f10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cm-header&quot;)/nav[@class=&quot;utility-nav&quot;]/div[@class=&quot;padded-container&quot;]/div[@class=&quot;hidden-xs hidden-sm&quot;]/ul[@class=&quot;horizontal-list&quot;]/li[3]/a[1]</value>
      <webElementGuid>2a3d423a-ba09-4ea8-92bc-9df07e7beaf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='cm-header']/nav/div/div/ul/li[3]/a</value>
      <webElementGuid>cdc38ed3-a9db-485d-9ad0-d924d511fbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Investors')]</value>
      <webElementGuid>383d3d0b-882b-4966-b90b-ccf8b546277f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/following::a[1]</value>
      <webElementGuid>c128eebb-05e8-4249-9ea6-b361f68640d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emerson.com'])[1]/following::a[2]</value>
      <webElementGuid>da8dc060-caf4-4fdb-9345-d8053a6b0c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Careers'])[1]/preceding::a[1]</value>
      <webElementGuid>c4902492-44bf-4112-9573-11dbe8515923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[2]</value>
      <webElementGuid>10a1322e-ad5e-4e36-809d-b642a0843956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Investors']/parent::*</value>
      <webElementGuid>d4e90131-87c7-46b7-a3a9-16f7ecf65413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.emerson.com/en-us/investors?_gl=1*ytxawz*_ga*MTUwOTg1ODIyMS4xNjUwODgxMTQ2*_ga_NW3KVPE6D0*MTY1MDg4MTE0NS4xLjEuMTY1MDg4MTE1NC4w')]</value>
      <webElementGuid>84ce7c50-7d4f-4021-8cde-db66ccc32910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[3]/a</value>
      <webElementGuid>ebbaa63f-23eb-49ee-9671-de907b4804bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.emerson.com/en-us/investors?_gl=1*ytxawz*_ga*MTUwOTg1ODIyMS4xNjUwODgxMTQ2*_ga_NW3KVPE6D0*MTY1MDg4MTE0NS4xLjEuMTY1MDg4MTE1NC4w' and (text() = 'Investors' or . = 'Investors')]</value>
      <webElementGuid>dc04bef4-4f76-4b07-a9eb-33042958d0dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
