<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_logonPassword</name>
   <tag></tag>
   <elementGuidId>34f5dc82-01cf-4d5e-99e7-570d625c3fee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WC_AccountDisplay_FormInput_logonPassword_In_Logon_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WC_AccountDisplay_FormInput_logonPassword_In_Logon_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc97b074-662f-469e-8c39-b191a5d38d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-padding</value>
      <webElementGuid>fb9c072a-2d7c-446a-956d-1da944870075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cec56893-fbb1-49b8-973d-f149efb531d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>3f9c4b0a-223c-4a29-b854-f23ba4bad800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>logonPassword</value>
      <webElementGuid>9601041f-497c-41a5-8acd-bb4ce4cd1725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>09295a2c-3cfb-428f-9b51-ebec22fa0da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2776ceb9-908b-4be2-a33e-db5f3c9d4683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WC_AccountDisplay_FormInput_logonPassword_In_Logon_1</value>
      <webElementGuid>be2eb5fe-d809-44c2-b7ec-9e2b75e29c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if(event.keyCode==13){ javascript:setDeleteCartCookie();validateForm();}</value>
      <webElementGuid>4c0dc24f-310a-400c-a211-ff0908f5e42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WC_AccountDisplay_FormInput_logonPassword_In_Logon_1&quot;)</value>
      <webElementGuid>2b4bb16f-207c-4cfc-bd95-d5648d5c7b0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WC_AccountDisplay_FormInput_logonPassword_In_Logon_1']</value>
      <webElementGuid>d1a3f979-e9a1-4931-8aef-c1f117ffd317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WC_AccountDisplay_div_7']/div[5]/div/input</value>
      <webElementGuid>19490e33-43ee-4c15-98af-9718e00a97f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>09d26585-a2e1-4aa9-88f4-965e32ad98b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'logonPassword' and @type = 'password' and @id = 'WC_AccountDisplay_FormInput_logonPassword_In_Logon_1']</value>
      <webElementGuid>7d02ba47-965d-48e9-ab5e-63222e9c50de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
